name: campestre
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.2
  cupertino_icons: ^0.1.3
  flutter_datetime_picker: ^1.5.1
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  #toast: ^0.1.5
  url_launcher: ^6.0.20
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.15
  #date_time_picker: ^2.1.0
  #intl: ^0.17.0
  dotted_border: ^2.0.0+2
  #share: ^0.6.4+3
  qr_flutter: ^4.0.0
  flutter_vector_icons: ^1.0.0
  esys_flutter_share_plus: ^2.1.0
  cloud_firestore: ^3.1.11
  firebase_core: any
  firebase_auth: ^3.3.12
  firebase_analytics: ^9.1.5
  firebase_storage: ^10.2.10
  image_picker: ^0.8.4+11
  crypto: ^3.0.1
  http: ^0.13.4
  oktoast: ^3.1.5
  fluttertoast: ^8.0.9
  time_range: ^1.0.2
  weekday_selector: ^1.1.0
  expandable: ^5.0.1
  flutter_stripe: ^2.5.0
  share_plus: ^4.0.4
  #Notificaciones
  firebase_messaging: ^11.2.12
  flutter_notification_channel: ^2.0.0
  platform: ^3.1.0
  get: ^4.6.1
  permission_handler: ^9.2.0
  share_files_and_screenshot_widgets: ^1.0.6
  flutter_shortener: ^0.3.1
  clipboard: ^0.1.3
  flutter_spinkit: ^5.1.0
  direct_select_flutter: ^1.1.1
  dio: ^4.0.6
  barcode_scan2: ^4.2.0
  qr_code_scanner: ^0.7.0
  flutter_pdfview: ^1.2.2
  
  
  date_format: ^2.0.6
  #firebase_messaging: any
  #device_info: ^0.4.2+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/campestre.jpeg"
  #flutter pub run flutter_launcher_icons:main

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/certificates/
    - assets/regula.license
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700