// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FDrFIT_pe4tBvw0twGfGmhVA8fkAtsw',
    appId: '1:803493939434:web:5e655f02046cb96ec26f93',
    messagingSenderId: '803493939434',
    projectId: 'communecampestre',
    authDomain: 'communecampestre.firebaseapp.com',
    databaseURL: 'https://communecampestre-default-rtdb.firebaseio.com',
    storageBucket: 'communecampestre.appspot.com',
    measurementId: 'G-62E5YSYJL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHgkewwoFe0LQXigKWj3tkfqMxPk4wjI',
    appId: '1:803493939434:android:b1995b1a96eb4117c26f93',
    messagingSenderId: '803493939434',
    projectId: 'communecampestre',
    databaseURL: 'https://communecampestre-default-rtdb.firebaseio.com',
    storageBucket: 'communecampestre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC73g-HpjebP08q0ZG-T5CxwYPXC9qu6OA',
    appId: '1:803493939434:ios:85a27c4bfffc6f29c26f93',
    messagingSenderId: '803493939434',
    projectId: 'communecampestre',
    databaseURL: 'https://communecampestre-default-rtdb.firebaseio.com',
    storageBucket: 'communecampestre.appspot.com',
    iosClientId: '803493939434-4nn3dgo87b4ndi76l6fqabr22lgujq76.apps.googleusercontent.com',
    iosBundleId: 'com.commune.campestre',
  );
}
