// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzA2ehUlv-pqO0652ktB0dCKEsHw536A',
    appId: '1:92424595254:web:1efb117576f79fd51f7597',
    messagingSenderId: '92424595254',
    projectId: 'commune-cf48f',
    authDomain: 'commune-cf48f.firebaseapp.com',
    databaseURL: 'https://commune-cf48f-default-rtdb.firebaseio.com',
    storageBucket: 'commune-cf48f.appspot.com',
    measurementId: 'G-BDTF4RDY7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-oROZ9NFqD4hteCnMUxOZLtSTcQhfMiw',
    appId: '1:92424595254:android:72bdee289363995b1f7597',
    messagingSenderId: '92424595254',
    projectId: 'commune-cf48f',
    databaseURL: 'https://commune-cf48f-default-rtdb.firebaseio.com',
    storageBucket: 'commune-cf48f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjf0zodLrk3eJySLWsOX30gTNaUK8y4gg',
    appId: '1:92424595254:ios:461167094b7682ea1f7597',
    messagingSenderId: '92424595254',
    projectId: 'commune-cf48f',
    databaseURL: 'https://commune-cf48f-default-rtdb.firebaseio.com',
    storageBucket: 'commune-cf48f.appspot.com',
    iosClientId: '92424595254-i3eqadu5hu1duluooadu57qrmncle6rm.apps.googleusercontent.com',
    iosBundleId: 'com.commune.campestre',
  );
}
